components:
  - !component
    name: component1
    type: firsttype
    configurations:
      Path: $MKVBINDDIR/firsttype/261
  - !component
    name: component2
    type: secondtype
    configurations:
      Path: $MKVBINDDIR/firsttype/261
  
